-- Lab 01

CREATE DATABASE lab01sql

use lab01sql

CREATE TABLE TB_DEPARTAMENTO (
  CD_DEPARTAMENTO INT NOT NULL PRIMARY KEY,
  NM_DEPARTAMENTO VARCHAR(50) NOT NULL
)

INSERT INTO TB_DEPARTAMENTO 
VALUES (1, 'TI'), (2, 'RH')


-------------------

CREATE TABLE TB_FUNCIONARIO (
   MATRICULA INT NOT NULL PRIMARY KEY,
   NOME VARCHAR(50) NOT NULL,
   CPF VARCHAR(13) NOT NULL UNIQUE,
   CD_DEPARTAMENTO INT NOT NULL REFERENCES 
   TB_DEPARTAMENTO (CD_DEPARTAMENTO)
)

INSERT INTO TB_FUNCIONARIO 
VALUES (10, 'JOAO', '3838883883',1)

------------------

CREATE TABLE TB_TELEFONE (
    MATRICULA INT NOT NULL REFERENCES
    TB_FUNCIONARIO (MATRICULA),
    TELEFONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (MATRICULA, TELEFONE)
)

INSERT INTO TB_TELEFONE
VALUES (10, '99999-9884'), (10,'98776-1234')

-----------------

CREATE TABLE TB_TERCEIRIZADO (
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
)

INSERT INTO TB_TERCEIRIZADO 
VALUES (100, 'MAURICIO')

----------------

CREATE TABLE TB_CATEGORIA_PROBLEMA (
    CD_CATEGORIA INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL,
)

INSERT INTO TB_CATEGORIA_PROBLEMA
VALUES (1000, 'HARDWARE'), (2000, 'SOFTWARE')

--------------------

CREATE TABLE TB_ATENDE (
    MATRICULA INT NOT NULL REFERENCES TB_TERCEIRIZADO(MATRICULA),
    CD_CATEGORIA  INT NOT NULL REFERENCES TB_CATEGORIA_PROBLEMA(CD_CATEGORIA),
    PRIMARY KEY (MATRICULA, CD_CATEGORIA)
)

INSERT INTO TB_ATENDE
VALUES (100,1000), (100,2000)

-----------------------


CREATE TABLE TB_SOLICITACAO (
    MATRICULA INT NOT NULL REFERENCES TB_FUNCIONARIO(MATRICULA),
    CD_CATEGORIA INT NOT NULL REFERENCES TB_CATEGORIA_PROBLEMA(CD_CATEGORIA),
    DT_ABERTURA DATETIME NOT NULL,
    DS_PROBLEMA VARCHAR(200) NULL,
    DT_FECHAMENTO DATETIME NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT('Em Aberto'),
    PRIMARY KEY (MATRICULA, CD_CATEGORIA,DT_ABERTURA)
)

ALTER TABLE TB_SOLICITACAO
ADD CONSTRAINT CK_STATUS CHECK (STATUS IN ('Em Aberto','Fechado','Cancelado'))

ALTER TABLE TB_SOLICITACAO
ADD CONSTRAINT CK_STATUS_DATA 
CHECK ((STATUS = 'Em Aberto' AND DT_FECHAMENTO IS NULL) OR
       (STATUS IN ('Fechado', 'Cancelado') AND DT_FECHAMENTO IS NOT NULL))
        
INSERT INTO TB_SOLICITACAO (MATRICULA,
                            CD_CATEGORIA,
                            DT_ABERTURA,
                            DS_PROBLEMA
                            )
                           
VALUES (10, 1000,'20190101','IMPRESSORA COM PROBLEMA')

INSERT INTO TB_SOLICITACAO (MATRICULA,
                            CD_CATEGORIA,
                            DT_ABERTURA,
                            DS_PROBLEMA,
                            DT_FECHAMENTO,
                            STATUS
                            )
                           
VALUES (10, 2000,'20190102','IMPRESSORA COM PROBLEMA','20190102', 'Cancelado')
        
SELECT * FROM TB_SOLICITACAO
   
    
   










